version: '3.3'

services:
  tiuha-postgres:
    image: postgres:12.2
    ports:
      - '5444:5432'
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tiuha"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: tiuha
      POSTGRES_PASSWORD: tiuha
      PGDATA: '/tmp/'
