{{- if and .Values.netatmo.enabled .Values.netatmo.buildconfig.enabled }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.netatmo.buildconfig.name }}
  namespace: {{ .Values.namespace }}
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.netatmo.buildconfig.name }}
  namespace: {{ .Values.namespace }}
spec:
  triggers:
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: 'ssh://git@github.fmi.fi/hav/tiuha.git'
      ref: main
    contextDir: local-env/netatmo/
  strategy:
    type: Docker
    dockerStrategy:
     dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.netatmo.buildconfig.name }}:latest
{{- end }}