{{- if and .Values.qc.enabled .Values.qc.buildConfig.enabled }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.qc.buildConfig.name }}
  namespace: {{ .Values.namespace }}
spec:
  lookupPolicy:
    local: false
  tags:
    - name: dev
      from:
        kind: DockerImage
        name: 'quay.io/fmi/tiuha-qc:dev'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.qc.buildConfig.name }}
  namespace: {{ .Values.namespace }}
spec:
  source:
    type: Git
    git:
      uri: 'ssh://git@github.fmi.fi/hav/tiuha.git'
      ref: main
    contextDir: 'qc/'
    sourceSecret:
      name: tiuha-openshift-image-builder
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      pullSecret: 
        name: dockerhub-partios
  output:
    to:
      kind: DockerImage
      name: quay.io/fmi/tiuha-qc:dev
    pushSecret:
      name: fmi-tiuha-pull-secret
{{- end }}