{{- if and .Values.localstack.enabled .Values.localstack.buildconfig.enabled }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.localstack.buildconfig.name }}
  namespace: {{ .Values.namespace }}
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.localstack.buildconfig.name }}
  namespace: {{ .Values.namespace }}
spec:
  triggers:
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: 'ssh://git@github.fmi.fi/hav/tiuha.git'
      ref: main
    contextDir: "local-env/localstack/"
    sourceSecret:
      name: tiuha-openshift-image-builder
  strategy:
    type: Docker
    dockerStrategy:
     dockerfilePath: Dockerfile
     pullSecret: 
        name: dockerhub-partios
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.localstack.buildconfig.name }}:latest
{{- end }}