apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: measurement-api2
  namespace: {{ .Values.namespace }}
spec:
  triggers:
    - type: ConfigChange
  source:
    dockerfile: |
      FROM maven:eclipse-temurin

      WORKDIR /app

      COPY . .

      #docker run -v ~/.m2:/var/maven/.m2 -it --rm -u $(id -u) -e MAVEN_CONFIG=/var/maven/.m2 maven mvn -Duser.home=/var/maven archetype:generate

      RUN mvn package -DskipTests -Duser.home=/var/maven

      RUN 

      CMD ["java", "-XX:MaxRAMPercentage=90", "-jar", "/app/target/measurement-api-1.0-SNAPSHOT-shaded.jar"]

  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      env:
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: measurement-api-envs
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: measurement-api-envs
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: measurement-api-envs
              key: DATABASE_NAME
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: measurement-api-envs
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: measurement-api-envs
              key: DATABASE_PASSWORD
        - name: GEOMESA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: measurement-api-envs
              key: GEOMESA_DB_PASSWORD
        - name: IMPORT_BUCKET
          valueFrom:
            secretKeyRef:
              name: measurement-api-envs
              key: IMPORT_BUCKET
        - name: MEASUREMENTS_BUCKET
          valueFrom:
            secretKeyRef:
              name: measurement-api-envs
              key: MEASUREMENTS_BUCKET
        - name: ENV
          valueFrom:
            secretKeyRef:
              name: measurement-api-envs
              key: ENV
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: measurement-api-envs
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: measurement-api-envs
              key: AWS_SECRET_ACCESS_KEY
  output:
    to:
      kind: ImageStreamTag
      name: measurement-api2:latest
