{{- if and .Values.measurementapi.enabled .Values.measurementapi.buildconfig.enabled }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.measurementapi.buildconfig.name }}
  namespace: {{ .Values.namespace }}
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.measurementapi.buildconfig.name }}
  namespace: {{ .Values.namespace }}
spec:
  triggers:
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: 'ssh://git@github.fmi.fi/hav/tiuha.git'
      ref: main
    contextDir: measurement-api/
    sourceSecret:
      name: tiuha-openshift-image-builder
  strategy:
    type: Docker
    dockerStrategy:
     dockerfilePath: Dockerfile
     pullSecret: 
        name: dockerhub-partios
     env:
     {{- range .Values.measurementapi.buildconfig.envs }}
        - name: {{ . }}
          valueFrom:
            secretKeyRef:
              name: measurement-api-envs
              key: {{ . }}
      {{- end }}
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.measurementapi.buildconfig.name }}:latest
{{- end }}