apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiuha-postgres-test
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-test
  template:
    metadata:
      labels:
        io.kompose.network/local-env-default: "true"
        app: postgres-test
    spec:
      containers:
        - args:
            - postgres
            - -c
            - log_statement=all
          env:
            - name: PGDATA
              value: /tmp/
            - name: POSTGRES_PASSWORD
              value: tiuha-test
            - name: POSTGRES_USER
              value: tiuha-test
          image: postgres:12.2
          livenessProbe:
            exec:
              command:
                - pg_isready -U tiuha-test
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: tiuha-postgres-test
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
