{{- if .Values.localstack.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-localstack
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-localstack
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/local-env-default: "true"
        app: s3-localstack
    spec:
      containers:
        - image: s3-localstack
          name: tiuha-s3
          ports:
            - containerPort: 4566
              hostIP: 127.0.0.1
            - containerPort: 4571
              hostIP: 127.0.0.1
          resources: {}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: {{ .Values.localstack.pvc.name }}
      restartPolicy: Always
      volumes:
        - name: {{ .Values.localstack.pvc.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.localstack.pvc.name }}
{{- end }}