{{- if .Values.measurementapi.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.measurementapi.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"{{ .Values.measurementapi.name }}:dev"},"fieldPath":"spec.template.spec.containers[?(@.name==\"{{ .Values.measurementapi.name }}\")].image"}]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.measurementapi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.measurementapi.name }}
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: measurement-api-envs
        image: image-registry.openshift-image-registry.svc:5000/{{ .Values.namespace }}/{{ .Values.measurementapi.name }}:dev
        imagePullPolicy: Always
        name: {{ .Values.measurementapi.name }}
        volumeMounts:
          - name: kubeconfig
            mountPath: /etc/kube
            readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          secretName: kubeconfig
{{- end }}