{{- if .Values.measurementapi.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.measurementapi.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.measurementapi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.measurementapi.name }}
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: measurement-api-envs
        image: image-registry.openshift-image-registry.svc:5000/tiuha-dev/{{ .Values.measurementapi.name }}:dev
        imagePullPolicy: Always
        name: {{ .Values.measurementapi.name }}
        volumeMounts:
          - name: kubeconfig
            mountPath: /etc/
            readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          secretName: kubeconfig
{{- end }}