{{- if .Values.localenv.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: local-env-default
  namespace: {{ .Values.namespace }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/local-env-default: "true"
  podSelector:
    matchLabels:
      io.kompose.network/local-env-default: "true"
{{- end }}