{{- if .Values.roleBindings.template.name }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBindings.template.name }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.roles.template.name }}
subjects:
- kind: ServiceAccount
  name: default
{{- end }}