{{- if .Values.roleBindings.batch.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBindings.batch.name }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.roles.batch.name }}
subjects:
- kind: ServiceAccount
  name: default
{{- end }}