{{- if .Values.measurementapi.route.enabled }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.measurementapi.name }}
  namespace: {{ .Values.namespace }}
spec:
  to:
    kind: Service
    name: {{ .Values.measurementapi.name }}
    weight: 100
  port:
    targetPort: '8383'
  {{- if .Values.measurementapi.route.tls }}
  tls:
    termination: edge
  {{- end }}
{{- end }}