{{- if .Values.netatmo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: netatmo-mock
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "1234"
      port: 1234
      targetPort: 8080
  selector:
    app: netatmo-mock
{{- end }}