{{- if .Values.externalPostgres.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: external-postgres-service
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.externalPostgres.name }}
{{- end }}