version: '3.3'

services:
  tiuha-postgres:
    image: postgres:12.2
    ports:
      - '5444:5432'
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tiuha"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: tiuha
      POSTGRES_PASSWORD: tiuha
      PGDATA: '/tmp/'
  tiuha-postgres-test:
    image: postgres:12.2
    ports:
      - '5445:5432'
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tiuha-test"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: tiuha-test
      POSTGRES_PASSWORD: tiuha-test
      PGDATA: '/tmp/'
  s3-localstack:
    build: ./localstack
    container_name: tiuha-s3
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  netatmo-mock:
    build: ./netatmo
    container_name: tiuha-netatmo
    ports:
      - "1234:80"