namespace: tiuha-dev

netatmo:
  enabled: true
  buildconfig: 
    enabled: true
    name: netatmo

localstack:
  enabled: true
  pvc:
    enabled: true
    name: s3-localstack-claim0
    size: 10Gi
  buildconfig:
    enabled: true
    name: localstack

postgres:
  enabled: false

postgresTest:
  enabled: false

localenv:
  enabled: true

measurementapi:
  enabled: true
  buildconfig:
    enabled: true
    name: measurement-api
    envs:
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_NAME
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - GEOMESA_DB_PASSWORD
      - IMPORT_BUCKET
      - MEASUREMENTS_BUCKET
      - ENV
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY