namespace: tiuha-dev

netatmo:
  enabled: true
  buildconfig: 
    enabled: true
    name: netatmo

localstack:
  enabled: true
  pvc:
    enabled: true
    name: s3-localstack-claim0
    size: 10Gi

postgres:
  enabled: true

postgresTest:
  enabled: true

localenv:
  enabled: true